### ISSUE TITLE
Quick re-design of webpage.

### ISSUE THREAD

**Issue by DallasLaComb** [DallasLaComb/Flag-Bingo-Project#1]
The website didn't look very good before, both from seeing the code and also from a user perspective it was very sloppy. We will keep the original versions code in a read only repository to source it later, however we do not plan on moving forward with any of this code if Dr. Mahoney approves our new design this Monday, 10/23/2023. This was what it originally looked like to user:
**Flag Selection:**
![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/88401844/46ea8579-f6e7-4cad-8f7c-40441a74d90a)
**Call Generator:** 
![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/88401844/c3779460-fa47-474a-b833-ac0db551b3da)

**Comment by DallasLaComb** [comment]
This is the Updated Design. One nice feature about the new design from the developer perspective is you can change each 'card' just by changing one of them in the javascript, because it dynamically adds the cards now, rather than copy and paste of html.

![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/88401844/3c010bc8-d0cc-4741-9922-b99b1e148b59)

**Comment by DallasLaComb** [comment]
![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/88401844/1219b1aa-188c-47a6-8b7a-8c2982291143)

On these I think it would look nice to add a "hamburger" type feature. Where you can hide flags for the continents or show them.

**Comment by DallasLaComb** [comment]
I think a "Sticky" "Generate Lobby" button might be a good idea as well, so that if you are on the flag selection lobby you can always see the "Generate Lobby" button. / Maybe Sticky NavBar is good idea too (?)

Sticky just means that even when you are scrolling, the button will still be visible on the clients screen. / I would think a small box in the bottom right would be good for this possibly, but can look more into this design element later. (I personally think sticky may be better just due to the fact that Africa has a lot more countries that the other continents. So after you select your flags, if you are a new user, it may not be super intuitive to know you have to scroll all the way down to click the "save lobbies" button")

**Comment by vinny2001** [comment]
Also, we will need to add a sub array for the nations/ territories in the Caribbean (which is represented as a category for selection in the old source code.

**Comment by DallasLaComb** [comment]
Updated the design some more. Now it uses "radio button" icons to show what you've selected...

![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/88401844/088e9f75-e5b8-4af0-9636-83229a67f9d7)



![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/88401844/27fe9b43-abe2-4f06-8360-cf5ba133319b)

When you click 'Play' at the bottom it now loads this screen with your selections:

![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/88401844/976be925-8d66-4f07-b615-de8344860381)

When you click play it also hides the elements for the flag selection...

**Comment by DallasLaComb** [comment]
![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/88401844/c9707e41-7d98-4fca-bcf9-8c51c8fb73f5)
