### ISSUE TITLE
Create "How To Play" Page

### ISSUE THREAD

**Issue by DallasLaComb** [DallasLaComb/Flag-Bingo-Project#10]
Create the page to teach new people "How to Play" / Use this web page. We will need to make it clear for people who are new to the site, that the intention of this site is to select flags, generate those cards, print those cards, and then randomly call those cards.

Make note to user that this is not a virtual bingo game / cards will need to be printed out by user...

**Comment by crcarta** [comment]
[fdasfsadf.pdf](https://github.com/DallasLaComb/Flag-Bingo-Project/files/13380358/fdasfsadf.pdf)

Plan is to work on how to play page, current idea is kind of modeled in pdf.

**Comment by crcarta** [comment]
Addition of 2 gifs and 1 photo. A very simple guide to getting started. Had longer version. Shortened for simplicity.

**Comment by crcarta** [comment]
![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/13405062/c00e2b90-355f-4628-ba39-028551001d92)

**Comment by crcarta** [comment]
![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/13405062/51371c9a-dfc5-4955-bbdc-9d41462a3015)

**Comment by crcarta** [comment]
Specifically, recap with team about if they want a "howto" for each of the options that save game html page presents. Assumption is they are straightforward enough. This could be incorrect.
