### ISSUE TITLE
Create "Saved Cards" Page

### ISSUE THREAD

**Issue by DallasLaComb** [DallasLaComb/Flag-Bingo-Project#20]
Created a design for the "Saved Cards" Page. It also pulls "lobby names" from cookies. The design currently looks like this: (This is the "Saved Cards" page, I just didn't set up the navbar to show that we're actually on that page color scheme wise... These changes are saved on "seperateHTMLs" branch currently, have not merged as of 11:34am 10/29/2023

![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/88401844/1c550e02-04c6-48da-9399-bb07f8def9f6)

Again, those names on the left are inserted via cookies, they each also have saved flags saved to them...

The idea with [play] [print] [edit] and [delete] being:

Play: Brings up call generator.

Print: Gives the user the generated cards for them to print.

Edit: Edit Lobby Name (Maybe edit flag selection for a lobby name too? Not sure how hard this would be, but probably possible)

Delete: Delete this lobby.

With edit, and delete: You'd have to update the cookie in the back obviously...

**Comment by vinny2001** [comment]
The main goal for sprint one was to get the "play" button functionality working, which involves loading the unique card set (flag names and images) from the browsers cookies and into the call generator. **THIS is done**

The rest of the functionality, (Edit, Print and Delete) will be worked on during Sprint 2.
