### ISSUE TITLE
Create logic after clicking "Save Cards" in the bottom right on "Generate Game" tab...

### ISSUE THREAD

**Issue by DallasLaComb** [DallasLaComb/Flag-Bingo-Project#21]
After you click "Save Cards" in the bottom right a screen will pop up like this: (Saved/Pushed to seperateHTMLs branch)

![Image](https://github.com/DallasLaComb/Flag-Bingo-Project/assets/88401844/b99eb49f-24e4-4c21-a6e3-2a27daa414a6)

When you click "submit" it will push your lobby name as well as your card selection to cookies... 

(I don't have logic to give the user feedback after they click submit / Also need to make sure that their lobby names are unique / limit characters / limit to 10 lobbies saved... )

**Comment by vinny2001** [comment]
This functionality has been present since Sprint 1, but we may still add a limit of lobbies

**Comment by vinny2001** [comment]
Decided to not add a limit of lobbies
