### ISSUE TITLE
Color scheme up to CCSU Standards / ARIA Compliant.

### ISSUE THREAD

**Issue by DallasLaComb** [DallasLaComb/Flag-Bingo-Project#6]
Will need to try to find what the CCSU Color standards are.

There is some websites out there where you can copy + paste your code such as HTML Validator, CSS Validator, ARIA Validator, etc to make sure that it is compliant for people with disabilities. I will link these sites when we get closer to time for this story.

**Comment by vinny2001** [comment]
As of 11/14 @vinny2001 has started implementing CCSU/ LALCC logos, accessibility standards, and UI/ color schemes as per the following document:

https://docs.ccsu.edu/Central-Brand-Guidelines.pdf

ARIA Compliance will be added/ tailored in future updates

**Comment by vinny2001** [comment]
As of today, I added ARIA compliance changes to all HTML files, improving their accessibility standards.
