### ISSUE TITLE
Create "About LALCC" Page

### ISSUE THREAD

**Issue by DallasLaComb** [DallasLaComb/Flag-Bingo-Project#8]
Create a page talking about what the LALCC is. Will ask DR.Mahoney what she wants on this page specifically. This is a bonus ticket, but should be easy to add: and gives us extra stuff for this project.

**Comment by crcarta** [comment]
Linked Button to LALCC CCSU mission page. Didn't realize this was a bonus reach. My mistake, delete if you want but I don't know if we need to actually make an About Me page since they already have one done for us.
